# Generated by Django 3.2.4 on 2021-06-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210622_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
