# Generated by Django 3.2.4 on 2021-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210622_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default=0, upload_to='videos'),
            preserve_default=False,
        ),
    ]
